version: '2'
services:
  web:
    image: artifactory.wikia-inc.com/mobile-wiki/mobile-wiki-devbox:latest
    ports:
      - "7001:7001"
    volumes:
      - ./:/app
    environment:
      - WIKIA_DATACENTER=$WIKIA_DATACENTER
      - WIKIA_ENVIRONMENT=$WIKIA_ENVIRONMENT
      - WIKIA_DEV_DOMAIN=$WIKIA_DEV_DOMAIN
      - INTERNAL_CACHE_HOST=dev.icache.service.$WIKIA_DATACENTER.consul
      - MOBILE_WIKI_LOG_TCP_PORT=9999
      - MOBILE_WIKI_LOG_TCP_HOST=logger
      - LOCAL_USER_ID=$LOCAL_USER_ID
    depends_on:
      - logger
    command: "npm run dev"
  logger:
    image: artifactory.wikia-inc.com/platform/fluentd_elastic:latest
    volumes:
      - ./fluent.conf:/fluentd/etc/config:ro
    command: "fluentd -c /fluentd/etc/config -v"
    environment:
      - HOST_HOSTNAME=$HOST_HOSTNAME