FROM alpine:3.3

RUN apk update
RUN apk add python py-pip py-setuptools git ca-certificates
RUN pip install python-dateutil

RUN git clone https://github.com/s3tools/s3cmd.git /opt/s3cmd
RUN ln -s /opt/s3cmd/s3cmd /usr/bin/s3cmd

WORKDIR /

ADD ./res /res
ADD ./sjc /sjc

# Folders for s3cmd optionations
RUN mkdir /opt/src
RUN mkdir /opt/dest

CMD ["s3cmd"]

