apiVersion: apps/v1
kind: Deployment
metadata:
  # wrapped with double quote (") to prevent issues with special characters in version name
  name: "mobile-wiki-prod-${version}"
  namespace: prod
  labels:
    app: mobile-wiki
    env: prod
    # wrapped with double quote (") to prevent issues with special characters in version name
    version: "${version}"
    status: active
spec:
  replicas: 16
  selector:
    matchLabels:
      app: mobile-wiki
      env: prod
      # wrapped with double quote (") to prevent issues with special characters in version name
      version: "${version}"
  template:
    metadata:
      labels:
        app: mobile-wiki
        env: prod
        # wrapped with double quote (") to prevent issues with special characters in version name
        version: "${version}"
        stage: mobile-wiki-prod
    spec:
      serviceAccountName: k8s-pod
      initContainers:
      - args:
        - secret/chef/google/analytics
        env:
        - name: VAULT_ADDR # This isn't required in prod but must be set for dev
          value: active.vault.service.${dc}.consul:8200
        name: secrets
        image: artifactory.wikia-inc.com/ops/init-vault:0.0.27
        imagePullPolicy: Always
        volumeMounts: # vault auth cert is read from here
        - name: secrets-dir # secrets are stored here
          mountPath: /var/lib/secrets
      containers:
      - name: mobile-wiki-prod
        image: ${image}
        livenessProbe:
          httpGet:
            path: /heartbeat
            port: 8001
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /heartbeat
            port: 8001
          periodSeconds: 5
        env:
          - name: WIKIA_ENVIRONMENT
            value: prod
          - name: WIKIA_DATACENTER
            value: ${dc}
          - name: INTERNAL_CACHE_HOST
            value: mediawiki-prod
        resources:
          requests:
            cpu: 0.4
            memory: 1.5Gi
          limits:
            memory: 2.5Gi
        ports:
        - containerPort: 8001
        - containerPort: 8007
        command: ["sh", "-c", "source /var/lib/secrets/export.env && exec npm run fastboot-server"]
        volumeMounts:
        - name: secrets-dir
          readOnly: true
          mountPath: /var/lib/secrets
      volumes:
        - name: secrets-dir # secrets will be stored here
          emptyDir:
            medium: Memory
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mobile-wiki-prod
  namespace: prod
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: mobile-wiki-prod.prod.${dc}.k8s.wikia.net
    http:
      paths:
      - backend:
          serviceName: mobile-wiki-prod
          servicePort: main
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mobile-wiki-prod
  labels:
    app: mobile-wiki
    env: prod
  namespace: prod
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: mobile-wiki
      env: prod
  namespaceSelector:
    matchNames:
      - prod
  endpoints:
    - port: admin
      path: /metrics
      interval: 10s
