apiVersion: v1
kind: Service
metadata:
  labels:
    app: mobile-wiki-${env}
  name: mobile-wiki-${env}
  namespace: prod
spec:
  ports:
  - protocol: TCP
    name: main
    port: 80
    targetPort: 8001
  selector:
    app: mobile-wiki-${env}
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mobile-wiki-${env}
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-wiki-${env}
  template:
    metadata:
      labels:
        app: mobile-wiki-${env}
    spec:
      containers:
      - name: mobile-wiki-${env}
        image: ${image}
        livenessProbe:
          httpGet:
            path: /heartbeat
            port: 8001
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /heartbeat
            port: 8001
          periodSeconds: 5
        env:
          - name: WIKIA_ENVIRONMENT
            value: prod
          - name: WIKIA_DATACENTER
            value: ${dc}
          - name: MEDIAWIKI_DOMAIN
            value: prod.icache.service.${dc}.consul
          - name: GA_USERID_SALT
            valueFrom:
              secretKeyRef:
                name: mobile-wiki
                key: gaUserIdSalt
        resources:
         requests:
           cpu: 0.4
           memory: 300Mi
        ports:
        - containerPort: 8001
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mobile-wiki-${env}
  namespace: prod
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: mobile-wiki-${env}.prod.${dc}.k8s.wikia.net
    http:
      paths:
      - backend:
          serviceName: mobile-wiki-${env}
          servicePort: main