apiVersion: v1
kind: Service
metadata:
  labels:
    app: mobile-wiki-prod
  name: mobile-wiki-prod
  namespace: prod
spec:
  ports:
  - protocol: TCP
    name: main
    port: 80
    targetPort: 8001
  selector:
    app: mobile-wiki-prod
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mobile-wiki-prod
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-wiki-prod
  template:
    metadata:
      labels:
        app: mobile-wiki-prod
    spec:
      containers:
      - name: mobile-wiki-prod
        image: artifactory.wikia-inc.com/test/mobile-wiki-prod:0.0.3
#        livenessProbe:
#          httpGet:
#            path: /healthcheck
#            port: 8081
#          initialDelaySeconds: 3
#          timeoutSeconds: 3
#          periodSeconds: 20
        env:
          - name: WIKIA_ENVIRONMENT
            value: prod
        resources:
         requests:
           cpu: 0.4
           memory: 300Mi
        ports:
        - containerPort: 7001
        - containerPort: 8001
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mobile-wiki-prod
  namespace: prod
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: mobile-wiki-prod.prod.sjc.k8s.wikia.net
    http:
      paths:
      - backend:
          serviceName: mobile-wiki-prod
          servicePort: main
